######################################################################
#
# File name : tb_top_ram_ctrl_wave.do
# Created on: Tue Jul 16 19:34:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
