######################################################################
#
# File name : tb_top_ram_ctrl_simulate.do
# Created on: Tue Jul 16 19:51:07 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_4 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_top_ram_ctrl xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_top_ram_ctrl_wave.do}

view wave
view structure
view signals

do {tb_top_ram_ctrl.udo}

run 1000ns
