######################################################################
#
# File name : tb_top_ram_ctrl_compile.do
# Created on: Tue Jul 16 19:51:05 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\edatools\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
D:\\edatools\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

D:\\edatools\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\edatools\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\edatools\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../ram_ctrl.srcs/sources_1/ip/blk_256x8/sim/blk_256x8.v" \
"../../../../ram_ctrl.srcs/top_ram_ctrl.v" \
"../../../../ram_ctrl.srcs/tb_top_ram_ctrl.v" \


# compile glbl module
D:\\edatools\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

