######################################################################
#
# File name : tb_top_flash_led_wave.do
# Created on: Wed Jul 10 21:22:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
