######################################################################
#
# File name : tb_top_flash_led_compile.do
# Created on: Wed Jul 10 22:01:26 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\edatools\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
D:\\edatools\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

D:\\edatools\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\edatools\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\edatools\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../flash_led.srcs/sources_1/new/top_flash_led.v" \
"../../../../flash_led.srcs/sim_1/new/tb_top_flash_led.v" \


# compile glbl module
D:\\edatools\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

